<a href="https://colab.research.google.com/github/AC-Pyre/Tensorflow_fundamentals/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to tensorflow

In [1]:
import tensorflow as tf
print(tf.__version__)
import numpy as np


2.5.0


In [2]:
# create tensors with tf.constant() 
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim()


TypeError: ignored

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector

In [ ]:
#check the dimention of our vector
vector.ndim

In [ ]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

In [ ]:
matrix.ndim

In [ ]:
# create another matrix
another_matrix = tf.constant([[10., 4.],
                              [3., 5.],
                              [7., 6.]], dtype=tf.float16) #specify datatype with dtype paramater
another_matrix

In [ ]:
# what's the number of dimensions of another matrix?
another_matrix.ndim

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]]) 
tensor

In [ ]:
tensor.ndim

# What we've created so far:
 * scalar: a single number
 * vector: a number with direction (e.g. wind speed and direction)
 * Matrix: a 2-dimensional array of numbers
 * tensor: an n-dimensionall array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1 dimensional tensor is a vector)

## creating tensors with tf.Variable

In [ ]:
# create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

In [ ]:
# lets change one of hte elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

In [ ]:
#how about we try .assign()
changeable_tensor[0].assign(6)
changeable_tensor

In [ ]:
# lets try and change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor


### creating random tensors
#### random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# let's create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducability
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor

In [4]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesnt effect learning
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

2

In [5]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [82]:
#shuffle our non-shuffled tensor
tf.random.set_seed(15)                    #global level seed
tf.random.shuffle(not_shuffled, seed=67)  #operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [7]:
tf.random.set_seed(15) 
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [8]:
# if we wnat our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level seed

### other ways to make tensors

In [9]:
# create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [10]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4)) # (rows, columns)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy and TensorFlow tensors is that tensors can be run on a GPU (much faster)


In [11]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [12]:
A = tf.constant(numpy_A, shape=(2, 3, 4)) # 2 * 3 * 4 = 24 You need the dimensions of the tensor to be the same as the number of elements in the array
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors
 * Shape - the lenght (number of elements) of each of the dimensions of a tensor.
  - tensor.shape

 * Rank - The number of tensor dimensions. A scalar has rank 0, vector has rank 1, matrix rank 2, tensor rank n.
  - tensor.ndim

 * Axis or Dimension - a particular dimension of a tensor
  - tensor[0], tensor [:, 1]

 * Size - the total number of items in the tensor.b
  - tf.size(tensor)

In [13]:
# create a rank 4 tensor
rank_4_tensors = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [14]:
rank_4_tensors.shape, rank_4_tensors.ndim, tf.size(rank_4_tensors)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [15]:
# get various attributes of our tensor
print("Datatypes of every element:", rank_4_tensors.dtype)
print("Number of dimensions (rank):", rank_4_tensors.ndim)
print("Shape of tensor:", rank_4_tensors.shape)
print("Elements along the 0 axis:", rank_4_tensors.shape[0])
print("Elements along the last axis:", rank_4_tensors.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensors).numpy())

Datatypes of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like python lists

In [16]:
# Ge the first 2 elements of each dimensions 
rank_4_tensors[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [17]:
some_list[:1]

NameError: ignored

In [ ]:
# get first element from each dimension from each index except fot he final one
rank_4_tensors[:1, :1, :1, :]

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]
rank_2_tensor


In [ ]:
# Add in extra dimensions to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # the ... signifies every axis before the last one
rank_3_tensor

In [ ]:
# alternative to tf.newaxis
y = tf.expand_dims(rank_2_tensor, axis=0)
y

In [ ]:
tf.expand_dims(y, axis=0)


### Manipulating tensors (tensor operations)
basic operations
+,-,*,/

In [18]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [19]:
# Original tensor is unchanged

In [20]:
# Multiplication also works
tensor * 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [21]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [22]:
# the tf. (tensorflow) version is gpu enabled for faster speed

***Matrix multiplication***

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfull if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions


In [23]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [24]:
# Matrix multiplication with Python operator "@"


In [25]:
my_tensor_1 = tf.constant([[1, 2, 1],
                           [0, 1, 0],
                           [2, 3, 4]])
my_tensor_2 = tf.constant([[2, 5],
                           [6, 7],
                           [1, 8]])


In [26]:
tf.matmul(my_tensor_1, my_tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [27]:
# Matrix multiplication with Python operator "@"
my_tensor_1 @ my_tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [28]:
# create a tensor (3, 2)
x = tf.constant([[1, 2],
                  [3, 4],
                  [5, 6]])
# creat another (3, 2) tensor
y = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [29]:
# try to matrix multiply tensors of same shape
x @ y

InvalidArgumentError: ignored

In [30]:
# change y matrix to support matrix multiplication
tf.reshape(y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [31]:
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [32]:
#try to change the shape of x instead of y
tf.matmul(tf.reshape(x, shape=(2, 3)), y)
# outside dimensions are 2 instead of 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [33]:
# Can do the same with transpose, transpose flips the axes 
x, tf.transpose(x), tf.reshape(x, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [34]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

you can perform matrix multiplication using:
* tf.matmul()
* tf.tensordot()
* @

In [35]:
# Perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(tf.transpose(x), y, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [36]:
# Perform the dot product on x and y transposed
tf.tensordot(x, tf.transpose(y), 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [37]:
# Perform matrix multiplication between x and y (reshaped)
tf.tensordot(x, tf.reshape(y, shape=(2, 3)), 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [38]:
# Check the values of y, reshape y and transpose y
print("normal y:", y )
print("y reshaped to (2, 3):", tf.reshape(y, (2, 3)))
print("y transposed:", tf.transpose(y))

normal y: tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
y reshaped to (2, 3): tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
y transposed: tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [39]:
# Generally, when performing matrix multiplications on two tensors and one fthe aex doesn't line up, 
# ...you will transpose (ranther than reshape) one of the tensors to satisfy the tensor multplication rules))

### Changing the datatype of a tensor

In [40]:
# Create a new tensor with the default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [41]:
C = tf.constant([1, 7])
C.dtype

tf.int32

In [42]:
# Change from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D, D.dtype


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [43]:
# change from int32 to float32
E = tf.cast(C, tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [44]:
# Get the absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* get the minimum
* get the maximum
* get the mean of a tensor
* get the sum of a tensor

In [45]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 5, 84, 58, 58, 31, 89, 97, 75,  1, 85, 33, 74, 28, 22, 22, 71, 57,
        1, 23,  7, 45, 41, 61, 45, 54, 44, 77,  7,  2,  1, 69, 28, 73, 31,
       52, 37, 96, 68, 97, 51, 73, 24, 70, 19, 97, 12, 64, 40, 71, 82])>

In [46]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [47]:
# Find the minimum
tf.reduce_min(E)


<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [48]:
# find maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [49]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [50]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2452>

In [51]:
import tensorflow_probability as tfp
# find the variance of our tensor
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=842>

In [52]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=29.02>

## Find the positional maximum and minimum

In [53]:
# Create a new tensor for finding positionlal minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [54]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [55]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [56]:
# Find the max vavlue of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [57]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [58]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [59]:
# Find the minimum using the postional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

* Removes dimensions of size 1 from the shape of a tensor

In [60]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [61]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [62]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors
* a form on numerical encoding using 0's and one 1

In [63]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Squareing, log, square root


In [64]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [65]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [66]:
# Find the square root
tf.math.sqrt(tf.cast(H, dtype=tf.float32))


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [67]:
# Find the log
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully wiht NumPy arrays.

In [68]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [69]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [70]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [71]:
# The defualt types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.])) # making a tensor form numpy array defaults to float64
tensor_J = tf.constant([3., 7., 10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)